# 🏋️‍♂️ Week 2 数据清洗专项 Gym (100题)

**目标**: 通过 100 道高强度针对性练习，彻底掌握 Pandas 数据清洗核心技能。
**数据集**: `nicapotato/womens-ecommerce-clothing-reviews` (真实电商评论数据)

**主要训练点 (针对你的薄弱项)**:
1.  **编码转换 (Encoding)**: `map`, `factorize`, `get_dummies`
2.  **文本清洗 (String)**: `str.contains`, `str.extract`, 正则表达式
3.  **复杂逻辑 (Complex Logic)**: `apply`, `groupby` + `transform`
4.  **性能 (Performance)**: 数据类型优化

---
**使用说明**:
1.  先运行 **数据准备** 代码块。
2.  逐个单元格完成练习。
3.  遇到困难查看 Pandas 文档，尽量避免直接查答案。

In [1]:
import pandas as pd
import numpy as np
import re

# 检查数据集是否存在，不存在则下载
import os
if not os.path.exists('./data/Womens Clothing E-Commerce Reviews.csv'):
    print("正在下载数据集...")
    !kaggle datasets download nicapotato/womens-ecommerce-clothing-reviews --path ./data --unzip
    print("下载完成。")
else:
    print("数据集已存在。")

# 加载数据
df = pd.read_csv('./data/Womens Clothing E-Commerce Reviews.csv', index_col=0)

# 初步查看
print(f"数据形状: {df.shape}")
df.head(3)

数据集已存在。
数据形状: (23486, 10)

,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
0,767,33,NaN,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates
1,1080,34,NaN,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses
2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses

### Q1. 查看 DataFrame 的前 5 行。

In [2]:
df.head()

,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
0,767,33,NaN,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates
1,1080,34,NaN,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses
2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses
3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants
4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses

### Q2. 查看 DataFrame 的后 5 行。

In [3]:
df.tail()

,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
23481,1104,34,Great dress for many occasions,I was very happy to snag this dress at such a ...,5,1,0,General Petite,Dresses,Dresses
23482,862,48,Wish it was made of cotton,"It reminds me of maternity clothes. soft, stre...",3,1,0,General Petite,Tops,Knits
23483,1104,31,"Cute, but see through","This fit well, but the top was very see throug...",3,0,1,General Petite,Dresses,Dresses
23484,1084,28,"Very cute dress, perfect for summer parties an...",I bought this dress for a wedding i have this ...,3,1,2,General,Dresses,Dresses
23485,1104,52,Please make more like this one!,This dress in a lovely platinum is feminine an...,5,1,22,General Petite,Dresses,Dresses

### Q3. 查看 DataFrame 的 随机 5 行 (sample)。

In [4]:
df.sample(5)

,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
20542,1053,38,Live in these,I could live in these. they are so comfy. i ty...,5,1,2,General Petite,Bottoms,Pants
15212,1033,40,Flattering cut,Really like these -- they fit really well and ...,5,1,3,General Petite,Bottoms,Jeans
9384,1059,41,Very unique and flattering,I tried this on as a fluke. i work at retaile...,5,1,4,General Petite,Bottoms,Pants
8093,936,64,NaN,Let me start off by saying that i really do li...,4,1,1,General,Tops,Sweaters
18812,862,35,Classy cowlneck,Absolutely love this sweater! it is a tad bit ...,5,1,0,General Petite,Tops,Knits

### Q4. 查看 DataFrame 的列名列表。

In [5]:
df.columns

Index(['Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

### Q5. 查看 DataFrame 的索引。

In [6]:
df.index

Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,     9,
       ...
       23476, 23477, 23478, 23479, 23480, 23481, 23482, 23483, 23484, 23485],
      dtype='int64', length=23486)

### Q6. 查看每一列的数据类型 (dtypes)。

In [7]:
df.dtypes

Clothing ID                 int64
Age                         int64
Title                      object
Review Text                object
Rating                      int64
Recommended IND             int64
Positive Feedback Count     int64
Division Name              object
Department Name            object
Class Name                 object
dtype: object

### Q7. 查看数据的基本信息 (info)。

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Clothing ID              23486 non-null  int64
 1   Age                      23486 non-null  int64
 2   Title                    19676 non-null  object
 3   Review Text              22641 non-null  object
 4   Rating                   23486 non-null  int64
 5   Recommended IND          23486 non-null  int64
 6   Positive Feedback Count  23486 non-null  int64
 7   Division Name            23472 non-null  object
 8   Department Name          23472 non-null  object
 9   Class Name               23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 2.0+ MB

### Q8. 查看数值型列的描述性统计 (describe)。

In [9]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Clothing ID,23486.0,NaN,NaN,NaN,918.118709,203.29898,0.0,861.0,936.0,1078.0,1205.0
Age,23486.0,NaN,NaN,NaN,43.198544,12.279544,18.0,34.0,41.0,52.0,99.0
Title,19676,13993,Love it!,136,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Review Text,22641,22634,Perfect fit and i've gotten so many compliment...,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rating,23486.0,NaN,NaN,NaN,4.196032,1.110031,1.0,4.0,5.0,5.0,5.0
Recommended IND,23486.0,NaN,NaN,NaN,0.822362,0.382216,0.0,1.0,1.0,1.0,1.0
Positive Feedback Count,23486.0,NaN,NaN,NaN,2.535936,5.702202,0.0,0.0,1.0,3.0,122.0
Division Name,23472,3,General,13850,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Department Name,23472,6,Tops,10468,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Class Name,23472,20,Dresses,6319,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Q9. 查看 'Department Name' 列的所有唯一值。

In [10]:
df['Department Name'].unique()

array(['Intimate', 'Dresses', 'Bottoms', 'Tops', 'Jackets', 'Trend', nan],
      dtype=object)

### Q10. 查看 'Division Name' 列的唯一值数量 (nunique)。

In [11]:
df['Department Name'].nunique()

6

### Q11. 统计 'Class Name' 各类别的出现频次 (value_counts)。

In [12]:
df['Class Name'].value_counts()

Class Name
Dresses           6319
Knits             4843
Blouses           3097
Sweaters          1428
Pants             1388
Jeans             1147
Fine gauge        1100
Skirts             945
Jackets            704
Lounge             691
Swim               350
Outerwear          328
Shorts             317
Sleep              228
Legwear            165
Intimates          154
Layering           146
Trend              119
Casual bottoms       2
Chemises             1
Name: count, dtype: int64

### Q12. 查看 'Review Text' 列是否有缺失值 (isnull)。

In [13]:
df['Review Text'].isnull().sum()

np.int64(845)

### Q13. 计算每一列的缺失值总数。

In [14]:
df.isnull().sum()

Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

### Q14. 计算每一列的缺失值百分比。

In [15]:
df.isnull().mean()

Clothing ID                0.000000
Age                        0.000000
Title                      0.162224
Review Text                0.035979
Rating                     0.000000
Recommended IND            0.000000
Positive Feedback Count    0.000000
Division Name              0.000596
Department Name            0.000596
Class Name                 0.000596
dtype: float64

### Q15. 选择 'Clothing ID' 和 'Age' 两列组成新的 DataFrame。

In [16]:
df_new = df[['Clothing ID','Age']]
df_new

       Clothing ID  Age
0              767   33
1             1080   34
2             1077   60
3             1049   50
4              847   47
...            ...  ...
23481         1104   34
23482          862   48
23483         1104   31
23484         1084   28
23485         1104   52

[23486 rows x 2 columns]

### Q16. 选择第 10 到 20 行数据 (iloc)。

In [17]:
df.iloc[10:20]

,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
10,1077,53,Dress looks like it's made of cheap material,Dress runs small esp where the zipper area run...,3,0,14,General,Dresses,Dresses
11,1095,39,NaN,This dress is perfection! so pretty and flatte...,5,1,2,General Petite,Dresses,Dresses
12,1095,53,Perfect!!!,More and more i find myself reliant on the rev...,5,1,2,General Petite,Dresses,Dresses
13,767,44,Runs big,Bought the black xs to go under the larkspur m...,5,1,0,Initmates,Intimate,Intimates
14,1077,50,Pretty party dress with some issues,This is a nice choice for holiday gatherings. ...,3,1,1,General,Dresses,Dresses
15,1065,47,"Nice, but not for my body",I took these out of the package and wanted the...,4,1,3,General,Bottoms,Pants
16,1065,34,"You need to be at least average height, or taller",Material and color is nice. the leg opening i...,3,1,2,General,Bottoms,Pants
17,853,41,Looks great with white pants,Took a chance on this blouse and so glad i did...,5,1,0,General,Tops,Blouses
18,1120,32,Super cute and cozy,"A flattering, super cozy coat. will work well...",5,1,0,General,Jackets,Outerwear
19,1077,47,Stylish and comfortable,I love the look and feel of this tulle dress. ...,5,1,0,General,Dresses,Dresses

### Q17. 选择索引为 100 的行 (loc)。

In [18]:
df.loc[100]

Clothing ID                                                              861
Age                                                                       39
Title                                                                  Comfy
Review Text                At first i wasn't sure about it. the neckline ...
Rating                                                                     4
Recommended IND                                                            1
Positive Feedback Count                                                    0
Division Name                                                 General Petite
Department Name                                                         Tops
Class Name                                                             Knits
Name: 100, dtype: object

### Q18. 重命名列 'Review Text' 为 'Review'。

In [19]:
df['Review'] = df['Review Text']

### Q19. 将列名全部转换为小写并替换空格为下划线 (e.g., 'Clothing ID' -> 'clothing_id')。

In [20]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(r' ','_',regex=True)
df.columns

Index(['clothing_id', 'age', 'title', 'review_text', 'rating',
       'recommended_ind', 'positive_feedback_count', 'division_name',
       'department_name', 'class_name', 'review'],
      dtype='object')

### Q20. 删除 'Title' 列 (drop)。

In [21]:
df.drop(columns=['title'])
df

,clothing_id,age,title,review_text,rating,recommended_ind,positive_feedback_count,division_name,department_name,class_name,review
0,767,33,NaN,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates,Absolutely wonderful - silky and sexy and comf...
1,1080,34,NaN,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses,Love this dress! it's sooo pretty. i happene...
2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses,I had such high hopes for this dress and reall...
3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants,"I love, love, love this jumpsuit. it's fun, fl..."
4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses,This shirt is very flattering to all due to th...
...,...,...,...,...,...,...,...,...,...,...,...
23481,1104,34,Great dress for many occasions,I was very happy to snag this dress at such a ...,5,1,0,General Petite,Dresses,Dresses,I was very happy to snag this dress at such a ...
23482,862,48,Wish it was made of cotton,"It reminds me of maternity clothes. soft, stre...",3,1,0,General Petite,Tops,Knits,"It reminds me of maternity clothes. soft, stre..."
23483,1104,31,"Cute, but see through","This fit well, but the top was very see throug...",3,0,1,General Petite,Dresses,Dresses,"This fit well, but the top was very see throug..."
23484,1084,28,"Very cute dress, perfect for summer parties an...",I bought this dress for a wedding i have this ...,3,1,2,General,Dresses,Dresses,I bought this dress for a wedding i have this ...
23485,1104,52,Please make more like this one!,This dress in a lovely platinum is feminine an...,5,1,22,General Petite,Dresses,Dresses,This dress in a lovely platinum is feminine an...

### Q21. 找出 'Review' 列为 NaN 的所有行。

In [22]:
df[df['review'].isnull() ]

,clothing_id,age,title,review_text,rating,recommended_ind,positive_feedback_count,division_name,department_name,class_name,review
92,861,23,NaN,NaN,5,1,0,General Petite,Tops,Knits,NaN
93,1081,31,NaN,NaN,5,1,0,General,Dresses,Dresses,NaN
98,1133,50,NaN,NaN,5,1,0,General,Jackets,Outerwear,NaN
135,861,35,NaN,NaN,4,1,0,General Petite,Tops,Knits,NaN
142,1126,35,NaN,NaN,5,1,0,General,Jackets,Outerwear,NaN
...,...,...,...,...,...,...,...,...,...,...,...
23258,862,35,NaN,NaN,4,1,0,General,Tops,Knits,NaN
23301,862,52,NaN,NaN,5,1,0,General,Tops,Knits,NaN
23303,823,46,NaN,NaN,5,1,0,General,Tops,Blouses,NaN
23470,1104,39,NaN,NaN,5,1,0,General Petite,Dresses,Dresses,NaN
23480,862,35,NaN,NaN,5,1,0,General Petite,Tops,Knits,NaN

### Q22. 删除 'Review' 列为 NaN 的行，并保存为 df_clean。

In [23]:
df_clean = df.dropna(subset='review')
df_clean

,clothing_id,age,title,review_text,rating,recommended_ind,positive_feedback_count,division_name,department_name,class_name,review
0,767,33,NaN,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates,Absolutely wonderful - silky and sexy and comf...
1,1080,34,NaN,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses,Love this dress! it's sooo pretty. i happene...
2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses,I had such high hopes for this dress and reall...
3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants,"I love, love, love this jumpsuit. it's fun, fl..."
4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses,This shirt is very flattering to all due to th...
...,...,...,...,...,...,...,...,...,...,...,...
23481,1104,34,Great dress for many occasions,I was very happy to snag this dress at such a ...,5,1,0,General Petite,Dresses,Dresses,I was very happy to snag this dress at such a ...
23482,862,48,Wish it was made of cotton,"It reminds me of maternity clothes. soft, stre...",3,1,0,General Petite,Tops,Knits,"It reminds me of maternity clothes. soft, stre..."
23483,1104,31,"Cute, but see through","This fit well, but the top was very see throug...",3,0,1,General Petite,Dresses,Dresses,"This fit well, but the top was very see throug..."
23484,1084,28,"Very cute dress, perfect for summer parties an...",I bought this dress for a wedding i have this ...,3,1,2,General,Dresses,Dresses,I bought this dress for a wedding i have this ...
23485,1104,52,Please make more like this one!,This dress in a lovely platinum is feminine an...,5,1,22,General Petite,Dresses,Dresses,This dress in a lovely platinum is feminine an...

### Q23. 使用 'Unknown' 填充 'Title' 列的缺失值。

In [24]:
df['title'] = df['title'].fillna('Unknown')
df

,clothing_id,age,title,review_text,rating,recommended_ind,positive_feedback_count,division_name,department_name,class_name,review
0,767,33,Unknown,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates,Absolutely wonderful - silky and sexy and comf...
1,1080,34,Unknown,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses,Love this dress! it's sooo pretty. i happene...
2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses,I had such high hopes for this dress and reall...
3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants,"I love, love, love this jumpsuit. it's fun, fl..."
4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses,This shirt is very flattering to all due to th...
...,...,...,...,...,...,...,...,...,...,...,...
23481,1104,34,Great dress for many occasions,I was very happy to snag this dress at such a ...,5,1,0,General Petite,Dresses,Dresses,I was very happy to snag this dress at such a ...
23482,862,48,Wish it was made of cotton,"It reminds me of maternity clothes. soft, stre...",3,1,0,General Petite,Tops,Knits,"It reminds me of maternity clothes. soft, stre..."
23483,1104,31,"Cute, but see through","This fit well, but the top was very see throug...",3,0,1,General Petite,Dresses,Dresses,"This fit well, but the top was very see throug..."
23484,1084,28,"Very cute dress, perfect for summer parties an...",I bought this dress for a wedding i have this ...,3,1,2,General,Dresses,Dresses,I bought this dress for a wedding i have this ...
23485,1104,52,Please make more like this one!,This dress in a lovely platinum is feminine an...,5,1,22,General Petite,Dresses,Dresses,This dress in a lovely platinum is feminine an...

### Q24. 使用 'Review' 列的众数填充该列的缺失值 (虽然不推荐文本这样填，练习一下 fillna)。

In [25]:
review_values_cnt = df['review'].value_counts().reset_index()
df['review'] = df['review'].fillna(review_values_cnt['review'].values[0])

### Q25. 检查是否存在完全重复的行 (duplicated)。

In [26]:
df.duplicated().sum()

np.int64(21)

### Q26. 计算重复行的数量。

In [27]:
df.duplicated().sum()

np.int64(21)

### Q27. 删除重复行，保留第一条出现的数据。

In [28]:
df.drop_duplicates(keep='first')

,clothing_id,age,title,review_text,rating,recommended_ind,positive_feedback_count,division_name,department_name,class_name,review
0,767,33,Unknown,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates,Absolutely wonderful - silky and sexy and comf...
1,1080,34,Unknown,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses,Love this dress! it's sooo pretty. i happene...
2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses,I had such high hopes for this dress and reall...
3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants,"I love, love, love this jumpsuit. it's fun, fl..."
4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses,This shirt is very flattering to all due to th...
...,...,...,...,...,...,...,...,...,...,...,...
23481,1104,34,Great dress for many occasions,I was very happy to snag this dress at such a ...,5,1,0,General Petite,Dresses,Dresses,I was very happy to snag this dress at such a ...
23482,862,48,Wish it was made of cotton,"It reminds me of maternity clothes. soft, stre...",3,1,0,General Petite,Tops,Knits,"It reminds me of maternity clothes. soft, stre..."
23483,1104,31,"Cute, but see through","This fit well, but the top was very see throug...",3,0,1,General Petite,Dresses,Dresses,"This fit well, but the top was very see throug..."
23484,1084,28,"Very cute dress, perfect for summer parties an...",I bought this dress for a wedding i have this ...,3,1,2,General,Dresses,Dresses,I bought this dress for a wedding i have this ...
23485,1104,52,Please make more like this one!,This dress in a lovely platinum is feminine an...,5,1,22,General Petite,Dresses,Dresses,This dress in a lovely platinum is feminine an...

### Q28. 删除重复行，保留最后一条出现的数据。

In [29]:
df.drop_duplicates(keep='last')

,clothing_id,age,title,review_text,rating,recommended_ind,positive_feedback_count,division_name,department_name,class_name,review
0,767,33,Unknown,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates,Absolutely wonderful - silky and sexy and comf...
1,1080,34,Unknown,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses,Love this dress! it's sooo pretty. i happene...
2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses,I had such high hopes for this dress and reall...
3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants,"I love, love, love this jumpsuit. it's fun, fl..."
4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses,This shirt is very flattering to all due to th...
...,...,...,...,...,...,...,...,...,...,...,...
23481,1104,34,Great dress for many occasions,I was very happy to snag this dress at such a ...,5,1,0,General Petite,Dresses,Dresses,I was very happy to snag this dress at such a ...
23482,862,48,Wish it was made of cotton,"It reminds me of maternity clothes. soft, stre...",3,1,0,General Petite,Tops,Knits,"It reminds me of maternity clothes. soft, stre..."
23483,1104,31,"Cute, but see through","This fit well, but the top was very see throug...",3,0,1,General Petite,Dresses,Dresses,"This fit well, but the top was very see throug..."
23484,1084,28,"Very cute dress, perfect for summer parties an...",I bought this dress for a wedding i have this ...,3,1,2,General,Dresses,Dresses,I bought this dress for a wedding i have this ...
23485,1104,52,Please make more like this one!,This dress in a lovely platinum is feminine an...,5,1,22,General Petite,Dresses,Dresses,This dress in a lovely platinum is feminine an...

### Q29. 针对 'clothing_id' 列，检查是否有重复 ID。

In [30]:
df['clothing_id'].duplicated().sum()

np.int64(22280)

### Q30. 假设 'clothing_id' 重复是正常的，找出 'review' 内容完全重复的刷单评论。

In [31]:
df[df['review'].duplicated() == True]

,clothing_id,age,title,review_text,rating,recommended_ind,positive_feedback_count,division_name,department_name,class_name,review
93,1081,31,Unknown,NaN,5,1,0,General,Dresses,Dresses,Perfect fit and i've gotten so many compliment...
98,1133,50,Unknown,NaN,5,1,0,General,Jackets,Outerwear,Perfect fit and i've gotten so many compliment...
135,861,35,Unknown,NaN,4,1,0,General Petite,Tops,Knits,Perfect fit and i've gotten so many compliment...
142,1126,35,Unknown,NaN,5,1,0,General,Jackets,Outerwear,Perfect fit and i've gotten so many compliment...
165,829,35,Unknown,NaN,3,0,0,General Petite,Tops,Blouses,Perfect fit and i've gotten so many compliment...
...,...,...,...,...,...,...,...,...,...,...,...
23258,862,35,Unknown,NaN,4,1,0,General,Tops,Knits,Perfect fit and i've gotten so many compliment...
23301,862,52,Unknown,NaN,5,1,0,General,Tops,Knits,Perfect fit and i've gotten so many compliment...
23303,823,46,Unknown,NaN,5,1,0,General,Tops,Blouses,Perfect fit and i've gotten so many compliment...
23470,1104,39,Unknown,NaN,5,1,0,General Petite,Dresses,Dresses,Perfect fit and i've gotten so many compliment...
23480,862,35,Unknown,NaN,5,1,0,General Petite,Tops,Knits,Perfect fit and i've gotten so many compliment...

### Q31. 创建一个包含缺失值的 Demo Series: `s = pd.Series([1, np.nan, 3, np.nan])`，使用前向填充 (ffill)。

In [32]:
s = pd.Series([1,np.nan,3,np.nan])
s_ffill = s.ffill()
s_ffill

0    1.0
1    1.0
2    3.0
3    3.0
dtype: float64

### Q32. 对上述 Series 使用后向填充 (bfill)。

In [33]:
s_bfill = s.bfill()
s_bfill

0    1.0
1    3.0
2    3.0
3    NaN
dtype: float64

### Q33. 对上述 Series 使用线性插值填充 (interpolate)。

In [34]:
s_inter = s.interpolate()
s_inter

0    1.0
1    2.0
2    3.0
3    3.0
dtype: float64

### Q34. 删除所有包含缺失值的列 (axis=1)。

In [35]:
df.dropna(axis=1)

,clothing_id,age,title,rating,recommended_ind,positive_feedback_count,review
0,767,33,Unknown,4,1,0,Absolutely wonderful - silky and sexy and comf...
1,1080,34,Unknown,5,1,4,Love this dress! it's sooo pretty. i happene...
2,1077,60,Some major design flaws,3,0,0,I had such high hopes for this dress and reall...
3,1049,50,My favorite buy!,5,1,0,"I love, love, love this jumpsuit. it's fun, fl..."
4,847,47,Flattering shirt,5,1,6,This shirt is very flattering to all due to th...
...,...,...,...,...,...,...,...
23481,1104,34,Great dress for many occasions,5,1,0,I was very happy to snag this dress at such a ...
23482,862,48,Wish it was made of cotton,3,1,0,"It reminds me of maternity clothes. soft, stre..."
23483,1104,31,"Cute, but see through",3,0,1,"This fit well, but the top was very see throug..."
23484,1084,28,"Very cute dress, perfect for summer parties an...",3,1,2,I bought this dress for a wedding i have this ...
23485,1104,52,Please make more like this one!,5,1,22,This dress in a lovely platinum is feminine an...

### Q35. 仅删除 'division_name' 列为空的行。

In [36]:
df.dropna(subset='division_name')

,clothing_id,age,title,review_text,rating,recommended_ind,positive_feedback_count,division_name,department_name,class_name,review
0,767,33,Unknown,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates,Absolutely wonderful - silky and sexy and comf...
1,1080,34,Unknown,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses,Love this dress! it's sooo pretty. i happene...
2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses,I had such high hopes for this dress and reall...
3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants,"I love, love, love this jumpsuit. it's fun, fl..."
4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses,This shirt is very flattering to all due to th...
...,...,...,...,...,...,...,...,...,...,...,...
23481,1104,34,Great dress for many occasions,I was very happy to snag this dress at such a ...,5,1,0,General Petite,Dresses,Dresses,I was very happy to snag this dress at such a ...
23482,862,48,Wish it was made of cotton,"It reminds me of maternity clothes. soft, stre...",3,1,0,General Petite,Tops,Knits,"It reminds me of maternity clothes. soft, stre..."
23483,1104,31,"Cute, but see through","This fit well, but the top was very see throug...",3,0,1,General Petite,Dresses,Dresses,"This fit well, but the top was very see throug..."
23484,1084,28,"Very cute dress, perfect for summer parties an...",I bought this dress for a wedding i have this ...,3,1,2,General,Dresses,Dresses,I bought this dress for a wedding i have this ...
23485,1104,52,Please make more like this one!,This dress in a lovely platinum is feminine an...,5,1,22,General Petite,Dresses,Dresses,This dress in a lovely platinum is feminine an...

### Q36. 找出 'age' 列中的异常值（假设 > 90 岁为异常）。

In [37]:
df[df['age']>90]

,clothing_id,age,title,review_text,rating,recommended_ind,positive_feedback_count,division_name,department_name,class_name,review
659,252,93,Amazing suit!,"This is by far the cutest, most glamorous one ...",5,1,3,Initmates,Intimate,Swim,"This is by far the cutest, most glamorous one ..."
6543,1095,94,Unknown,Flattering! i love how it looks like a maxi dr...,4,1,0,General,Dresses,Dresses,Flattering! i love how it looks like a maxi dr...
8327,1078,99,Beachy and boho!,I love the weight of the material; sometimes c...,5,1,1,General,Dresses,Dresses,I love the weight of the material; sometimes c...
9513,871,91,Unknown,"From the website picture (in particular, the g...",5,1,15,General,Tops,Knits,"From the website picture (in particular, the g..."
10617,1028,91,Pajama jeans,"I love the coh fleetwood jeans, and since i wa...",2,0,3,General,Bottoms,Jeans,"I love the coh fleetwood jeans, and since i wa..."
10686,1002,91,Unknown,NaN,5,1,0,General,Bottoms,Skirts,Perfect fit and i've gotten so many compliment...
11545,949,99,Unknown,"Great quality, i didn't expect the neck to be ...",4,1,4,General,Tops,Sweaters,"Great quality, i didn't expect the neck to be ..."
14997,1025,92,The only jeans you'll ever wear!,It's hard to tell how jeans will fit when shop...,5,1,2,General,Bottoms,Jeans,It's hard to tell how jeans will fit when shop...
15802,1028,91,Cut so small!,"These are the very stretchy, almost spongy, ty...",3,0,0,General Petite,Bottoms,Jeans,"These are the very stretchy, almost spongy, ty..."
17578,901,93,Very pretty & soft,Great quality. very versatile design and super...,4,1,0,General,Tops,Fine gauge,Great quality. very versatile design and super...
18036,1094,94,Unknown,Dress just did not fit will around the hips. ...,1,0,0,General,Dresses,Dresses,Dress just did not fit will around the hips. ...
18563,1094,94,Great dress!,"This dress is very comfortable, not itchy at a...",5,1,1,General,Dresses,Dresses,"This dress is very comfortable, not itchy at a..."
19304,1103,91,I don't understand this dress,I have been continually disappointed in retail...,1,0,3,General,Dresses,Dresses,I have been continually disappointed in retail...

### Q37. 将 'age' 大于 90 的值替换为 90。

In [38]:
df['age'] = df.loc[df['age']>90] = 90

### Q38. 计算 'rating' 列的平均值，忽略 NaN。

In [39]:
np.mean(df['rating'])

np.float64(4.196031678446734)

### Q39. 找出 'rating' 为空的数据（如果有），并用平均值填充。

In [40]:
rating_mean = np.mean(df['rating'])
df['rating'] = df['rating'].fillna(rating_mean)

### Q40. 再次检查清洗后的 df 是否还有缺失值。

In [41]:
df.isnull().sum()

clothing_id                  0
age                          0
title                        0
review_text                845
rating                       0
recommended_ind              0
positive_feedback_count      0
division_name               14
department_name             14
class_name                  14
review                       0
dtype: int64

### Q41. 将 'clothing_id' 转换为字符串类型 (astype)。

In [42]:
df['clothing_id'].astype(str)

0         767
1        1080
2        1077
3        1049
4         847
         ...
23481    1104
23482     862
23483    1104
23484    1084
23485    1104
Name: clothing_id, Length: 23486, dtype: object

### Q42. 检查 'age' 列是否为整数类型。

In [43]:
df['age'].dtypes

dtype('int64')

### Q43. 将 'age' 列转换为 float 类型。

In [44]:
df['age'].astype(float)

0        90.0
1        90.0
2        90.0
3        90.0
4        90.0
         ...
23481    90.0
23482    90.0
23483    90.0
23484    90.0
23485    90.0
Name: age, Length: 23486, dtype: float64

### Q44. 在 'review' 列中，计算每个评论的字符长度，存为新列 'review_len'。

In [45]:
df['review_len'] = df['review'].str.len()

### Q45. 在 'review' 列中，将所有文本转换为小写。

In [46]:
df['review'].str.lower()

0        absolutely wonderful - silky and sexy and comf...
1        love this dress!  it's sooo pretty.  i happene...
2        i had such high hopes for this dress and reall...
3        i love, love, love this jumpsuit. it's fun, fl...
4        this shirt is very flattering to all due to th...
                               ...
23481    i was very happy to snag this dress at such a ...
23482    it reminds me of maternity clothes. soft, stre...
23483    this fit well, but the top was very see throug...
23484    i bought this dress for a wedding i have this ...
23485    this dress in a lovely platinum is feminine an...
Name: review, Length: 23486, dtype: object

### Q46. 检查 'review' 列中是否包含 'dress' (不区分大小写)。

In [47]:
df['review'].str.contains('dress')

0        False
1         True
2         True
3        False
4        False
         ...
23481     True
23482    False
23483    False
23484     True
23485     True
Name: review, Length: 23486, dtype: bool

### Q47. 筛选出所有评论中包含 'love' 的行。

In [48]:
df['review'].str.contains('love')

0        False
1         True
2        False
3         True
4         True
         ...
23481    False
23482    False
23483    False
23484    False
23485     True
Name: review, Length: 23486, dtype: bool

### Q48. 使用正则提取 'review' 中出现的第一个数字 (str.extract)。

In [49]:
df['review'].str.extract(r'(\d+)')

         0
0      NaN
1        5
2      NaN
3      NaN
4      NaN
...    ...
23481  NaN
23482  NaN
23483  NaN
23484  NaN
23485  NaN

[23486 rows x 1 columns]

### Q49. 去除 'division_name' 列中可能存在的首尾空格 (strip)。

In [50]:
df['division_name'].str.strip()

0             Initmates
1               General
2               General
3        General Petite
4               General
              ...
23481    General Petite
23482    General Petite
23483    General Petite
23484           General
23485    General Petite
Name: division_name, Length: 23486, dtype: object

### Q50. 将 'class_name' 中的 'Intimates' 替换为 'Lingerie' (replace)。

In [51]:
df['class_name'].str.replace('Intimates','Lingerid')

0        Lingerid
1         Dresses
2         Dresses
3           Pants
4         Blouses
           ...
23481     Dresses
23482       Knits
23483     Dresses
23484     Dresses
23485     Dresses
Name: class_name, Length: 23486, dtype: object

### Q51. 将 'review' 中的标点符号去除 (使用正则替换)。

In [52]:
df['review'].str.replace(r'[^\w\s]', '', regex=True) #不会写标点符号正则

0        Absolutely wonderful  silky and sexy and comfo...
1        Love this dress  its sooo pretty  i happened t...
2        I had such high hopes for this dress and reall...
3        I love love love this jumpsuit its fun flirty ...
4        This shirt is very flattering to all due to th...
                               ...
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes soft stretc...
23483    This fit well but the top was very see through...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: review, Length: 23486, dtype: object

### Q52. 统计 'review' 中单词的个数（假设以空格分隔），存为 'word_count'。

In [53]:
df['word_count'] = df['review'].str.split().apply(len)

df[['word_count','review']].head()

   word_count                                             review
0           8  Absolutely wonderful - silky and sexy and comf...
1          62  Love this dress!  it's sooo pretty.  i happene...
2          98  I had such high hopes for this dress and reall...
3          22  I love, love, love this jumpsuit. it's fun, fl...
4          36  This shirt is very flattering to all due to th...

### Q53. 筛选出 'word_count' 大于 50 的详细评论。

In [54]:
df.loc[df['word_count']>50][['review','word_count']]

                                                  review  word_count
1      Love this dress!  it's sooo pretty.  i happene...          62
2      I had such high hopes for this dress and reall...          98
5      I love tracy reese dresses, but this one is no...          98
6      I aded this in my basket at hte last mintue to...         101
7      I ordered this in carbon for store pick up, an...          97
...                                                  ...         ...
23473  Great quality and extremely flattering. bonus ...          98
23474  Yes, this is a great dress! i wasn't sure abou...         103
23477  I'm so impressed with the beautiful color comb...          86
23479  So i wasn't sure about ordering this skirt bec...          97
23484  I bought this dress for a wedding i have this ...          86

[13302 rows x 2 columns]

### Q54. 检查 'department_name' 是否以 'T' 开头 (startswith)。

In [55]:
df['department_name'].str.startswith('T')

0        False
1        False
2        False
3        False
4         True
         ...
23481    False
23482     True
23483    False
23484    False
23485    False
Name: department_name, Length: 23486, dtype: object

### Q55. 将 'review' 列中的 'great' 替换为 'awesome'。

In [56]:
df['review'] = df['review'].str.replace('great','awesome')
df['review'].unique()

array(['Absolutely wonderful - silky and sexy and comfortable',
       'Love this dress!  it\'s sooo pretty.  i happened to find it in a store, and i\'m glad i did bc i never would have ordered it online bc it\'s petite.  i bought a petite and am 5\'8".  i love the length on me- hits just a little below the knee.  would definitely be a true midi on someone who is truly petite.',
       'I had such high hopes for this dress and really wanted it to work for me. i initially ordered the petite small (my usual size) but i found this to be outrageously small. so small in fact that i could not zip it up! i reordered it in petite medium, which was just ok. overall, the top half was comfortable and fit nicely, but the bottom half had a very tight under layer and several somewhat cheap (net) over layers. imo, a major design flaw was the net over layer sewn directly into the zipper - it c',
       ...,
       "This fit well, but the top was very see through. this never would have worked for me. i'm glad i was able to try it on in the store and didn't order it online. with different fabric, it would have been awesome.",
       "I bought this dress for a wedding i have this summer, and it's so cute. unfortunately the fit isn't perfect. the medium fits my waist perfectly, but was way too long and too big in the bust and shoulders. if i wanted to spend the money, i could get it tailored, but i just felt like it might not be worth it. side note - this dress was delivered to me with a nordstrom tag on it and i found it much cheaper there after looking!",
       'This dress in a lovely platinum is feminine and fits perfectly, easy to wear and comfy, too! highly recommend!'],
      dtype=object)

### Q56. 截取 'review' 列的前 20 个字符作为 'review_preview'。

In [57]:
df['review_preview'] = df['review'].str.slice(0,20)
df['review_preview']

0        Absolutely wonderful
1        Love this dress!  it
2        I had such high hope
3        I love, love, love t
4        This shirt is very f
                 ...
23481    I was very happy to
23482    It reminds me of mat
23483    This fit well, but t
23484    I bought this dress
23485    This dress in a love
Name: review_preview, Length: 23486, dtype: object

### Q57. 将 'division_name' 和 'department_name' 拼接成新列 'full_dept'，用 ' - ' 连接。

In [58]:
df['full_dept'] = df['division_name'] + '_' + df['department_name']

### Q58. 如果 'review' 为空，填充为 'No Review'，否则保持原样 (结合 fillna 或 where)。

In [59]:
df['review'] = df['review'].fillna('No Review')

### Q59. 找出 'class_name' 中包含 's' 的所有类别。

In [60]:
df.loc[df['class_name'].str.contains('s',case = False,na=False) == True]['class_name'].unique()

array(['Intimates', 'Dresses', 'Pants', 'Blouses', 'Knits', 'Sweaters',
       'Skirts', 'Sleep', 'Jackets', 'Swim', 'Jeans', 'Shorts',
       'Casual bottoms', 'Chemises'], dtype=object)

### Q60. 使用 split 将 'full_dept' 拆分回两列。

In [61]:
df['full_dept'].str.split('_',expand=True)

                    0         1
0           Initmates  Intimate
1             General   Dresses
2             General   Dresses
3      General Petite   Bottoms
4             General      Tops
...               ...       ...
23481  General Petite   Dresses
23482  General Petite      Tops
23483  General Petite   Dresses
23484         General   Dresses
23485  General Petite   Dresses

[23486 rows x 2 columns]

### Q61. 查看 'rating' 列的唯一值，确认为有序类别。

In [62]:
df['rating'].unique()

array([4, 5, 3, 2, 1])

### Q62. 使用 `map` 将 'rating' (1-5) 映射为情感 ('Bad', 'Poor', 'Neutral', 'Good', 'Great')。

In [63]:
rating_map = {
    1:'bad',
    2:'poor',
    3:'neutral',
    4:'good',
    5:'great'
}

df['rating'] = df['rating'].map(rating_map)
df['rating']

0           good
1          great
2        neutral
3          great
4          great
          ...
23481      great
23482    neutral
23483    neutral
23484    neutral
23485      great
Name: rating, Length: 23486, dtype: object

### Q63. 将 'recommended_ind' (0/1) 映射为 ('Not Recommended', 'Recommended')。

In [64]:
recommended_map = {
    0:'not recommended',
    1:'recommended'
}

df['recommended_ind'] = df['recommended_ind'].map(recommended_map)
df['recommended_ind']

0            recommended
1            recommended
2        not recommended
3            recommended
4            recommended
              ...
23481        recommended
23482        recommended
23483    not recommended
23484        recommended
23485        recommended
Name: recommended_ind, Length: 23486, dtype: object

### Q64. 使用 `pd.cut` 将 'age' 分箱：<30 'Young', 30-50 'Adult', >50 'Senior'。

In [65]:
# pd.cut(df['age'],df['age']<30,) # 不太会

### Q65. [重点] 使用 `pd.get_dummies` 对 'division_name' 进行 One-Hot 编码。

In [66]:
pd.get_dummies(df['division_name'])

       General  General Petite  Initmates
0        False           False       True
1         True           False      False
2         True           False      False
3        False            True      False
4         True           False      False
...        ...             ...        ...
23481    False            True      False
23482    False            True      False
23483    False            True      False
23484     True           False      False
23485    False            True      False

[23486 rows x 3 columns]

### Q66. [重点] 对 'department_name' 进行 Label Encoding (使用 `astype('category').cat.codes`)。

In [67]:
# df['department_name'].astype('catrgory').cat.codes

### Q67. [重点] 使用 `factorize` 对 'class_name' 进行编码。

In [68]:
# df['class_name'].factorize() # 没学过这个？

### Q68. 编写自定义函数 `categorize_length(len)`: <50 'Short', 50-100 'Medium', >100 'Long'。

In [69]:
def categorize_length(len):
    if len < 50:
        'short'
    elif len <100:
        'medium'
    else:
        'long'

### Q69. 将上述函数应用到 'review_len' 列 (apply)。

In [70]:
df['review_len'].apply(categorize_length)

0        None
1        None
2        None
3        None
4        None
         ...
23481    None
23482    None
23483    None
23484    None
23485    None
Name: review_len, Length: 23486, dtype: object

### Q70. 使用 lambda 函数将 'age' 增加 1。

In [71]:
# 没学过

### Q71. 对 'rating' 列使用 lambda 函数：如果 >3 返回 'Positive' 否则 'Negative'。

In [72]:
# 没学过

### Q72. 按 'division_name' 分组，计算 'rating' 的平均值。

In [73]:
df.groupby('division_name')['rating'].agg(['sum','count']) # 感觉写的不对

                                                              sum  count
division_name
General         greatneutralgreatpoorgreatgreatneutralneutralg...  13850
General Petite  greatgreatgoodgreatgreatgreatgreatgreatgoodgoo...   8120
Initmates       goodgreatneutralgreatgreatgreatgoodpoorgoodbad...   1502

### Q73. 按 'department_name' 分组，计算 'age' 的中位数和 'rating' 的平均值 (agg)。

In [74]:
# df.groupby('department_name')['age','rating'].agg({'age':'mean()','rating':'mean()'})
# 唉……

### Q74. 按 'division_name' 分组，获取每组 'rating' 最大值对应的行 (idxmax + loc)。

In [ ]:
# df.loc[df.groupby('division_name')['rating'].max()]

KeyError: "None of [Index(['poor', 'poor', 'poor'], dtype='object')] are in the [index]"

### Q75. [难点] 按 'class_name' 分组，计算每个评论长度的 z-score (transform)。

### Q76. 使用 pivot_table 查看不同 'division_name' 和 'department_name' 下的平均 'rating'。

### Q77. 使用 crosstab 查看 'rating' 和 'recommended_ind' 的频数分布。

### Q78. 将 Q76 的透视表结果重置索引 (reset_index)。

In [ ]:
# .reste_index()

### Q79. 筛选出 'age' 在 30-40 之间 且 'rating' 为 5 的数据 (boolean indexing)。

In [ ]:
# df[ [df['age']<40 ]& [df['age']>30 ] &[df['rating'] == 5]]

TypeError: unsupported operand type(s) for &: 'list' and 'list'

### Q80. 使用 query 方法实现 Q79 的筛选。

In [ ]:
# 没学过

### Q81. 找出评论最长的那条数据的完整信息。

In [80]:
df['review'].loc[df['review'].str.len().max()]

"Love love this dress. fits so awesome. i normally wouldn't have picked this dress. more preppy than my normal style. fits amazing. my hubby has complimented me more on this dress than anything else i've ever owned. the fit & flare style is super flattering i felt it fit tts."

### Q82. 找出 'rating' 为 5 但 'recommended_ind' 为 0 的矛盾数据。

In [ ]:
# df[[df['rating'] == 5] & [df['recommended_ind'] == 0]]

TypeError: unsupported operand type(s) for &: 'list' and 'list'

### Q83. 计算每个 'class_name' 的好评率 (rating >= 4 的比例)。

In [87]:
calss_name_good = df.groupby('class_name')['rating'].value_counts().rename('counts')
calss_name_good
class_name_good_rate = calss_name_good[calss_name_good['rating'] >= 4]/calss_name_good.groupby('class_name')['counts'].sum()

KeyError: 'rating'

### Q84. 筛选出评论中包含 'size' 的评论，并统计这些评论的平均评分。

In [89]:
df[df['review'].str.contains('size')].mean(df['rating'])

TypeError: unhashable type: 'Series'

### Q85. 对 'review' 列进行简单的词频统计（拆分单词，explode，value_counts）。

In [92]:
df['review'].str.split(' ').explode().value_counts()

review
the                     74257
i                       49828
and                     49327
a                       42605
it                      37145
                        ...
et                          1
mending,                    1
expected.\r\nperfect        1
looser/bigger               1
platinum                    1
Name: count, Length: 40814, dtype: int64

### Q86. [优化] 检查当前 DataFrame 的内存占用 (memory_usage)。

In [ ]:
# 没学过

### Q87. [优化] 将 object 类型的列转换为 category 类型以节省内存。

In [ ]:
# 没学过

### Q88. [优化] 再次检查内存占用，计算节省了多少空间。

In [ ]:
# 没学过

### Q89. 随机打乱 DataFrame 的行顺序 (sample frac=1)。

In [ ]:
# 没学过

### Q90. 按 'clothing_id' 排序，如果相同按 'age' 降序排列。

In [ ]:
df.sort_values(by='clothing_id',ascending=False)

### Q91. 找出 'review' 中包含连续 3 个以上感叹号的评论。

In [94]:
df[df['review'].str.contains(r'!!!',regex=True)]['review']

4        This shirt is very flattering to all due to th...
273      Bought both colors in xs and soooooo glad i di...
281      This dress is gorgeous!!! i love it! i bought ...
316      I really like this blouse a lot. very very eas...
412      I saw this dress online and immediately went t...
                               ...
23211    This is a lovely little nightie. i am a size 8...
23239    I just go these socks in one of my beauty boxe...
23381    I tried this dress on on a whim and will defin...
23421    Love, love this tunic. my size 4 fits perfectl...
23440    I tried on this dress in the store and was ple...
Name: review, Length: 403, dtype: object

### Q92. 提取 'review' 中提到的所有价格（假设以 $ 开头，正则）。

In [101]:
df['review'].str.extract(r'$(\d+)')

         0
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
...    ...
23481  NaN
23482  NaN
23483  NaN
23484  NaN
23485  NaN

[23486 rows x 1 columns]

### Q93. 计算 'positive_feedback_count' 与 'rating' 的相关系数 (corr)。

In [ ]:
df.corr(df[''],df[''])

### Q94. 绘制 'age' 的分布直方图 (hist)。

In [105]:
import matplotlib as plt
import seabron as sns
sns.hitplot(data=df,x='age',y=df['age'].value_counts)

ModuleNotFoundError: No module named 'seabron'

### Q95. 绘制 'rating' 的箱线图 (boxplot)。

In [107]:
sns.boxplot(data=df,y='rating')

NameError: name 'sns' is not defined

### Q96. 尝试使用 groupby 和 filter：保留平均评分大于 4 的 'class_name' 的所有数据。

In [ ]:
df.filter(df.groupby('calss_name')['rating'] >4)

### Q97. 滑动窗口：计算 'rating' 列的 3 行移动平均值 (rolling)。

In [ ]:
df['rating'].shift(3).rolling().mean()

### Q98. 将 'age' 列偏移 1 行 (shift) 生成新列。

In [ ]:
df['shifted_age'] = df['age'].shift(1)

### Q99. 比较 'age' 和 'shifted_age' 的差值。

In [ ]:
df['age'] - df['shifted_age']

### Q100. 你已完成 100 题！保存最终清洗好的数据为 'cleaned_reviews.csv'。

In [ ]:
# 没学过