# 🧩 Module B: Lambda & Apply 专项训练 (15 min)

**目标**: 征服 Pandas 中最灵活的武器——`lambda` 匿名函数。
1.  **Series Apply**: 对一列数据做处理 (一维)
2.  **DataFrame Apply**: 对一行数据做处理 (二维，`axis=1`)

**核心口诀**: 
- 简单逻辑用 lambda (`lambda x: x+1`)
- 复杂逻辑写 def (`def complex_logic(x): ...`)

In [1]:
import pandas as pd

# 🎓 学生成绩表 (极简版)
df = pd.DataFrame({
    'Student': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Math': [85, 45, 92, 60, 78],
    'English': [90, 50, 88, 55, 82],
    'Attendance': [100, 80, 95, 60, 100]  # 出勤率 %
})

df

   Student  Math  English  Attendance
0    Alice    85       90         100
1      Bob    45       50          80
2  Charlie    92       88          95
3    David    60       55          60
4      Eva    78       82         100

### Q1. (Lambda 基础) 给 'Math' 成绩加 5 分 (Series Apply)。
语法: `df['Math'].apply(lambda x: ...)`

In [2]:
# Your code here
df.columns = df.columns.str.lower()
df

   student  math  english  attendance
0    Alice    85       90         100
1      Bob    45       50          80
2  Charlie    92       88          95
3    David    60       55          60
4      Eva    78       82         100

In [3]:
df['math'] = df['math'].apply(lambda x: x + 5)
df

   student  math  english  attendance
0    Alice    90       90         100
1      Bob    50       50          80
2  Charlie    97       88          95
3    David    65       55          60
4      Eva    83       82         100

### Q2. (Lambda 逻辑) 判断 'English' 成绩：>=60 为 'Pass'，否则 'Fail'。
提示: `lambda x: 'Pass' if ... else 'Fail'`

In [6]:
# Your code here
df['english'].apply(lambda x : 'pass' if x >= 60 else 'fail')

0    pass
1    fail
2    pass
3    fail
4    pass
Name: english, dtype: object

### Q3. (DataFrame Apply - 难点) 计算总评级 (Final_Grade)。
规则: 
- if Math >= 90 **and** English >= 90 -> 'A'
- else -> 'B'

**注意**:
1.  这是对**一行**数据 (row) 操作，需要 `axis=1`。
2.  lambda 的输入 `x` 不再是单个数值，而是一行 Series (`x['Math']`, `x['English']`)。

In [7]:
# Your code here
df[['math','english']].apply(lambda x : 'A' if (x['math'] >= 90) & (x['english'] >= 90) else 'b',axis = 1)

0    A
1    b
2    b
3    b
4    b
dtype: object

### Q4. (复杂逻辑 - Def) 自定义函数 `evaluate_student(row)`。
规则:
- if Attendance < 70 -> 'Drop' (缺勤太多直接挂)
- elif (Math + English) / 2 >= 80 -> 'Excellent'
- else -> 'Normal'

请定义这个函数，并应用到 DataFrame 上生成 'Status' 列。

In [13]:
# Your code here
def evaluate_student(row):
    if row['attendance']< 70 :
        return 'drop'
    elif (row['math']+row['english'])/2 >= 80:
        return 'excellent'
    else:
        return 'normal'

df['status'] = df.apply(evaluate_student,axis = 1)
df

   student  math  english  attendance     status
0    Alice    90       90         100  excellent
1      Bob    50       50          80     normal
2  Charlie    97       88          95  excellent
3    David    65       55          60       drop
4      Eva    83       82         100  excellent