# 🧩 Module A: GroupBy 专项训练 (15 min)

**目标**: 彻底搞懂 `groupby` 的三种核心操作：
1.  **Aggregation (聚合)**: `agg` (变短)
2.  **Transformation (变换)**: `transform` (变长/保持原样)
3.  **Filtration (过滤)**: `filter` (删行)

**规则**: 不许查 CV, 不许查 AI，只凭直觉写。报错了不要紧，看错误提示。

In [1]:
import pandas as pd

# 🛒 超市销售数据 (极简版)
df = pd.DataFrame({
    'City': ['Beijing', 'Beijing', 'Beijing', 'Shanghai', 'Shanghai', 'Shanghai', 'Shenzhen', 'Shenzhen'],
    'Product': ['Apple', 'Banana', 'Orange', 'Apple', 'Banana', 'Banana', 'Apple', 'Orange'],
    'Sales': [100, 200, 150, 300, 100, 100, 500, 200],
    'Profit': [10, 50, 20, 80, 20, 20, 100, 40]
})

df

       City Product  Sales  Profit
0   Beijing   Apple    100      10
1   Beijing  Banana    200      50
2   Beijing  Orange    150      20
3  Shanghai   Apple    300      80
4  Shanghai  Banana    100      20
5  Shanghai  Banana    100      20
6  Shenzhen   Apple    500     100
7  Shenzhen  Orange    200      40

### Q1. (热身) 计算每个城市 ('City') 的总销售额 ('Sales')。

In [2]:
# Your code here
df.columns = df.columns.str.lower()
# df
df.groupby('city')['sales'].sum()

city
Beijing     450
Shanghai    500
Shenzhen    700
Name: sales, dtype: int64

### Q2. (进阶) 按城市分组，同时计算：
1.  `Sales` 的总和 (sum)
2.  `Profit` 的平均值 (mean)
3.  `Product` 的数量 (count)

**要求**: 使用 `agg()` 字典写法。

In [11]:
# Your code here
df.groupby('city').agg(
    total_sales=('sales','sum'),
    mean_profit=('profit','mean'),
    product_cnt=('product','count')
)

          total_sales  mean_profit  product_cnt
city
Beijing           450    26.666667            3
Shanghai          500    40.000000            3
Shenzhen          700    70.000000            2

### Q3. (命名聚合) 重复 Q2，但要求结果列名为：
- `Total_Sales`
- `Avg_Profit`
- `Product_Count`

**提示**: `agg(新列名=('原列名', '函数名'))`

In [12]:
# Your code here
# Your code here
df.groupby('city').agg(
    total_sales=('sales','sum'),
    avg_profit=('profit','mean'),
    product_cnt=('product','count')
)

          total_sales  avg_profit  product_cnt
city
Beijing           450   26.666667            3
Shanghai          500   40.000000            3
Shenzhen          700   70.000000            2

### Q4. (Transform) 计算每个产品在各城市的销售额占比。
公式: `Sales` / 该城市总Sales
**提示**: 需要用到 `groupby('City')['Sales'].transform('sum')`

In [13]:
# Your code here
df['sales'] / df.groupby('city')['sales'].transform('sum')

0    0.222222
1    0.444444
2    0.333333
3    0.600000
4    0.200000
5    0.200000
6    0.714286
7    0.285714
Name: sales, dtype: float64

### Q5. (Filter) 筛选出那些“总利润 (Profit Sum) > 100”的城市的所有数据。
**预期结果**:
Beijing: 10+50+20 = 80 (Fail)
Shanghai: 80+20+20 = 120 (Pass)
Shenzhen: 100+40 = 140 (Pass)

*结果应包含 Shanghai 和 Shenzhen 的所有行。*

In [16]:
# Your code here
df.groupby('city').filter(lambda x: x['profit'].sum() > 100)

       city product  sales  profit
3  Shanghai   Apple    300      80
4  Shanghai  Banana    100      20
5  Shanghai  Banana    100      20
6  Shenzhen   Apple    500     100
7  Shenzhen  Orange    200      40