# 🧩 Module C: Complex Filtering 专项训练 (15 min)

**目标**: 成为数据筛选的“狙击手”。
1.  **Boolean Indexing**: `&` (且), `|` (或), `~` (非)
2.  **String Filtering**: `str.contains` (包含), `str.startswith` (开头)
3.  **Query Syntax**: 像写 SQL 一样写筛选

**核心坑点**:
- 多条件必须加括号 `(A) & (B)`
- 永远不要用 `and`/`or`

In [1]:
import pandas as pd

# 🎬 电影评分数据 (极简版)
df = pd.DataFrame({
    'Title': ['Iron Man', 'Iron Man 2', 'Avengers', 'Batman', 'Batwoman', 'Spider-Man'],
    'Genre': ['Action', 'Action', 'Action/Sci-Fi', 'Crime', 'Crime', 'Action'],
    'Rating': [8.5, 7.0, 9.0, 8.8, 4.5, 7.5],
    'Year': [2008, 2010, 2012, 1989, 2019, 2002]
})

df

        Title          Genre  Rating  Year
0    Iron Man         Action     8.5  2008
1  Iron Man 2         Action     7.0  2010
2    Avengers  Action/Sci-Fi     9.0  2012
3      Batman          Crime     8.8  1989
4    Batwoman          Crime     4.5  2019
5  Spider-Man         Action     7.5  2002

### Q1. (多条件基础) 找出 'Action' 类电影 **且** 评分 > 8.0 的电影。
提示: `(条件1) & (条件2)`

In [2]:
# Your code here
df.columns = df.columns.str.lower()
df[(df['genre'] == 'Action') & (df['rating'] > 8.0)]

      title   genre  rating  year
0  Iron Man  Action     8.5  2008

### Q2. (字符串筛选) 找出所有**标题**中包含 'Man' 的电影。
提示: `str.contains()`

In [4]:
# Your code here
df.loc[df['title'].str.contains('Man')]

        title   genre  rating  year
0    Iron Man  Action     8.5  2008
1  Iron Man 2  Action     7.0  2010
5  Spider-Man  Action     7.5  2002

### Q3. (取反运算) 找出**年份不是** 2010 和 2012 的电影。
方法1: `~df['Year'].isin(...)`
方法2: `(df['Year'] != ...) & ...` (不推荐)

In [5]:
# Your code here
df.loc[~df['year'].isin([2010, 2012])]

        title   genre  rating  year
0    Iron Man  Action     8.5  2008
3      Batman   Crime     8.8  1989
4    Batwoman   Crime     4.5  2019
5  Spider-Man  Action     7.5  2002

### Q4. (Query 魔法) 用 `query()` 写法找出：
Genre 是 'Crime' **或者** Rating < 6.0 的电影。
提示: `query('条件 or 条件')`，注意字符串要引号包裹。

In [ ]:
# Your code here
df.query((df['genre'] == "Crime") or (df['rating'] < 6.0))

ValueError: expr must be a string to be evaluated, <class 'pandas.core.series.Series'> given