# 🏋️‍♂️ Week 2 Extra: 数据清洗专项健身房 (Data Cleaning Gym)

> **你的痛点，就是你的增肌点。**
> 就在刚刚，我们在 `to_datetime` 和 `groupby` 上摔了一跤。没关系，那里是 Pandas 最滑的地方。
> 这个 Notebook 不讲新课，只有**针对性更强、重复度更高**的机械训练。

---

## 🛠️ 准备活动：生成脏数据
不做任何修改，直接运行生成一份“糟糕”的数据。

In [1]:
import pandas as pd
import numpy as np

data = {
    'date': ['2023-01-01', '01/02/2023', '2023.01.03', 'invalid_date', '2023-01-05'],
    'category': ['A', 'A', 'B', 'B', 'C'],
    'amount': ['$100', '200', '300.5', '400', '500'],
    'user': ['u1', 'u1', 'u2', 'u2', 'u3']
}

df = pd.DataFrame(data)
df

           date category amount user
0    2023-01-01        A   $100   u1
1    01/02/2023        A    200   u1
2    2023.01.03        B  300.5   u2
3  invalid_date        B    400   u2
4    2023-01-05        C    500   u3

## ⚔️ 第一组训练：日期解析 (Date Parsing)
**痛点回忆**：默认解析会报错，或者解析不全。
**目标**：把 `date` 列转为标准日期格式 `YYYY-MM-DD`，处理不了的变成 `NaT`。

In [3]:
# [👉 请在这个单元格写代码]
# 提示：pd.to_datetime(..., format='mixed', errors='coerce')
df['date'] = pd.to_datetime(df['date'], format='mixed', errors='coerce')
df

        date category amount user
0 2023-01-01        A   $100   u1
1 2023-01-02        A    200   u1
2 2023-01-03        B  300.5   u2
3        NaT        B    400   u2
4 2023-01-05        C    500   u3

## ⚔️ 第二组训练：数值回魂 (Numeric Conversion)
**痛点回忆**：`$100` 是字符串，没法求和。
**目标**：
1. 去掉 `amount` 列里的 `$` 符号。
2. 把它转为 `float` 类型。

In [4]:
# [👉 请在这个单元格写代码]
df['amount'] = df['amount'].str.replace('$','').astype(float)
df

        date category  amount user
0 2023-01-01        A   100.0   u1
1 2023-01-02        A   200.0   u1
2 2023-01-03        B   300.5   u2
3        NaT        B   400.0   u2
4 2023-01-05        C   500.0   u3

## ⚔️ 第三组训练：分组聚合 (Group By)
**痛点回忆**：**List/Set 不是 DataFrame**。要用 `groupby` 这种“魔法”来变出新表。
**目标**：
按 `user` 分组，算出：
1. `sum`: 总金额
2. `count`: 消费次数

最后生成一个新的 `user_stats` DataFrame。

In [12]:
# [👉 请在这个单元格写代码]
# 核心口诀：df.groupby('谁')['算谁'].agg(['怎么算'])
user_stats = df.groupby('user')['amount'].agg(['sum', 'count']).reset_index()

user_stats

  user    sum  count
0   u1  300.0      2
1   u2  700.5      2
2   u3  500.0      1

## 🏁 冷却时间
做完了吗？如果这三组动作能流畅做完，今天的知识点你就已经形成了肌肉记忆！💪